name: Cypress Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    cypress:
        runs-on: ubuntu-latest

        services:
            docker:
                image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
                options: --privileged

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm install

            - name: Run Cypress tests in Docker
              run: |
                  docker run --rm -v $PWD:/e2e -w /e2e cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1 \
                    npx cypress run

name: Playwright Tests

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    playwright:
        runs-on: ubuntu-latest

        services:
            docker:
                image: mcr.microsoft.com/playwright:v1.39.0-jammy
                options: --privileged

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20'

            - name: Install dependencies
              run: npm install

            - name: Run Playwright tests in Docker
              run: |
                  docker run --rm -v $PWD:/e2e -w /e2e mcr.microsoft.com/playwright:v1.39.0-jammy \
                    npx playwright test
